[build]
  command = "npm install"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200


[functions]

    [functions.node_bundle]
    external_node_modules = [
      "module-one",
      "module-two"
    ]