
[build]
  command = "npm install ejs --save && npm install && npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[functions]

  [functions.node_bundle]
  external_node_modules = ["ejs"]

[build.environment]
  NODE_ENV = "production"